version: 0.2

# AWS CodeBuild build specification for a Vite + TypeScript React app
# Outputs static assets from the dist/ directory as build artifacts

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies with npm ci"
      - npm ci
  build:
    commands:
      - echo "Building application"
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete dist s3://$S3_BUCKET_NAME
      - aws cloudfront create-invalidation --distribution-id $CF_ID --paths /index.html


cache:
  paths:
    - node_modules/**/*
    - ~/.npm/**/*

artifacts:
  base-directory: dist
  files:
    - '**/*'
  discard-paths: no

